export const JobOptions = [
    "Software Engineer",
    "Doctor/Physician",
    "Teacher/Educator",
    "Nurse",
    "Accountant",
    "Engineer (various disciplines)",
    "Lawyer",
    "Sales Representative",
    "Marketing Specialist",
    "Project Manager",
    "Software Developer/Engineer",
    "Doctor/Physician",
    "Teacher/Educator",
    "IT Professional",
    "Engineer (various disciplines)",
    "Accountant",
    "Marketing Specialist",
    "Sales Representative",
    "Business Analyst",
    "Pharmacist",
    "Software Developer/Engineer",
    "Doctor/Physician",
    "Teacher/Educator",
    "IT Professional",
    "Engineer (various disciplines)",
    "Accountant",
    "Marketing Specialist",
    "Sales Representative",
    "Business Analyst",
    "Pharmacist",
    "Nurse",
    "Architect",
    "Journalist",
    "Graphic Designer",
    "Web Developer",
    "Chef",
    "Human Resources Specialist",
    "Data Scientist",
    "Financial Analyst",
    "Psychologist",
    "Lawyer/Attorney",
    "Police Officer",
    "Military Personnel",
    "Dentist",
    "Biologist",
    "Chemist",
    "Librarian",
    "Social Worker",
    "Public Relations Specialist",
    "Fashion Designer",
    "Electrician",
    "Plumber",
    "Carpenter",
    "Mechanic",
    "Pilot",
    "Flight Attendant",
    "Interior Designer",
    "Translator/Interpreter",
    "Actuary",
    "Economist",
    "Geologist",
    "Meteorologist",
    "Physiotherapist",
    "Optometrist",
    "Radiographer",
    "Paramedic",
    "Speech Therapist",
    "Phlebotomist",
    "Veterinarian",
    "Zoologist",
    "Botanist",
    "Ecologist",
    "Astronomer",
    "Astrophysicist",
    "Forensic Scientist",
    "Mathematician",
    "Statistician",
    "Sociologist",
    "Anthropologist",
    "Political Scientist",
    "Philosopher",
    "Historian",
    "Archaeologist",
    "Curator",
    "Tour Guide",
    "Event Planner",
    "Film Director",
    "Producer",
    "Actor/Actress",
    "Screenwriter",
    "Cinematographer",
    "Sound Engineer",
    "Animator",
    "Game Developer",
    "Biomedical Engineer",
    "Environmental Scientist",
    "Marine Biologist",
    "Oceanographer",
    "Wildlife Biologist",
    "Agricultural Scientist",
    "Biotechnologist",
    "Geneticist",
    "Immunologist",
    "Pharmacologist",
    "Forester",
    "Horticulturist",
    "Urban Planner",
    "Surveyor",
    "Civil Engineer",
    "Structural Engineer",
    "Materials Engineer",
    "Industrial Designer",
    "Quality Assurance Engineer",
    "Technical Writer",
    "Editor",
    "Proofreader",
    "Copywriter",
    "Translator",
    "Foreign Correspondent",
    "Cartoonist",
    "Illustrator",
    "Animator",
    "Game Designer",
    "User Experience (UX) Designer",
    "User Interface (UI) Designer",
    "Product Designer",
    "Brand Strategist",
    "Digital Marketing Specialist",
    "SEO Specialist",
    "Content Creator",
    "Podcaster",
    "Social Media Manager",
    "Community Manager",
    "Data Analyst",
    "Database Administrator",
    "Network Administrator",
    "Systems Administrator",
    "Information Security Analyst",
    "Computer Programmer",
    "Software Tester",
    "Technical Support Specialist",
    "IT Consultant",
    "Project Manager",
    "Business Development Manager",
    "Operations Manager",
    "Supply Chain Manager",
    "Logistics Manager",
    "Quality Control Manager",
    "Customer Service Representative",
    "Call Center Agent",
    "Retail Salesperson",
    "Cashier",
    "Store Manager",
    "Buyer",
    "Merchandiser",
    "Real Estate Agent",
    "Property Manager",
    "Construction Manager",
    "Surveyor",
    "Landscaper",
    "Interior Decorator",
    "Architectural Drafter",
    "Electrical Engineer",
    "Mechanical Engineer",
    "Chemical Engineer",
    "Biomedical Engineer",
    "Aerospace Engineer",
    "Nuclear Engineer",
    "Materials Engineer",
    "Petroleum Engineer",
    "Mining Engineer",
    "Geotechnical Engineer",
    "Environmental Engineer",
    "Water Resources Engineer",
    "Transportation Engineer",
    "Structural Engineer",
    "Robotics Engineer",
    "Renewable Energy Engineer",
    "Industrial Engineer",
    "Manufacturing Engineer",
    "Process Engineer",
    "Quality Control Engineer",
    "Safety Engineer",
    "Systems Engineer",
    "Research Scientist",
    "Lab Technician",
    "Clinical Research Coordinator",
    "Medical Technologist",
    "Forensic Scientist",
    "Epidemiologist",
    "Public Health Educator",
    "Healthcare Administrator",
    "Health Informatics Specialist",
    "Clinical Psychologist",
    "Counselor",
    "Social Worker",
    "Behavior Analyst",
    "Speech-Language Pathologist",
    "Occupational Therapist",
    "Physical Therapist",
    "Dietitian/Nutritionist",
    "Exercise Physiologist",
    "Athletic Trainer",
    "Sports Coach",
    "Personal Trainer",
    "Massage Therapist",
    "Yoga Instructor",
    "Fitness Instructor",
    "Dentist",
    "Dental Hygienist",
    "Orthodontist",
    "Oral and Maxillofacial Surgeon",
    "Veterinarian",
    "Veterinary Technician",
    "Pet Groomer",
    "Zoologist",
    "Wildlife Biologist",
    "Marine Biologist",
    "Botanist",
    "Ecologist",
    "Forester",
    "Agricultural Scientist",
    "Farm Manager",
    "Agronomist",
    "Horticulturist",
    "Florist",
    "Agricultural Extension Officer",
    "Environmental Scientist",
    "Environmental Consultant",
    "Environmental Engineer",
    "Climate Scientist",
    "Meteorologist",
    "Oceanographer",
    "Seismologist",
    "Volcanologist",
    "Geographer",
    "Cartographer",
    "Urban Planner",
    "Landscape Architect",
    "Surveyor",
    "Civil Engineer",
    "Structural Engineer",
    "Transportation Engineer",
    "Electrical Engineer",
    "Mechanical Engineer",
    "Chemical Engineer",
    "Materials Engineer",
    "Automotive Engineer",
    "Aerospace Engineer",
    "Biomedical Engineer",
    "Nuclear Engineer",
    "Robotics Engineer",
    "Energy Engineer",
    "Renewable Energy Engineer",
    "Power Systems Engineer",
    "Computer Engineer",
    "Software Engineer",
    "Network Engineer",
    "Telecommunications Engineer",
    "Database Administrator",
    "System Administrator",
    "Information Security Analyst",
    "Data Scientist",
    "Machine Learning Engineer",
    "Artificial Intelligence (AI) Engineer",
    "Robotics Engineer",
    "Mechatronics Engineer",
    "Electronics Engineer",
    "Embedded Systems Engineer",
    "Control Systems Engineer",
    "Biotechnology Engineer",
    "Bioprocess Engineer",
    "Genetic Engineer",
    "Biomedical Engineer",
    "Pharmaceutical Engineer",
    "Chemical Analyst",
    "Process Engineer",
    "Quality Control Engineer",
    "Health and Safety Engineer",
    "Materials Scientist",
    "Metallurgical Engineer",
    "Mining Engineer",
    "Geotechnical Engineer",
    "Petroleum Engineer",
    "Environmental Engineer",
    "Water Resources Engineer",
    "Transportation Engineer",
    "Structural Engineer",
    "Construction Manager",
    "Architectural Drafter",
    "Land Surveyor",
    "Landscape Architect",
    "Interior Designer",
    "Urban Planner",
    "Civil Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Chemical Engineer",
    "Automotive Engineer",
    "Aerospace Engineer",
    "Nuclear Engineer",
    "Materials Engineer",
    "Industrial Engineer",
    "Manufacturing Engineer",
    "Process Engineer",
    "Quality Control Engineer",
    "Safety Engineer",
    "Systems Engineer",
    "Robotics Engineer",
    "Renewable Energy Engineer",
    "Energy Engineer",
    "Power Systems Engineer",
    "Research Scientist",
    "Lab Technician",
    "Clinical Research Coordinator",
    "Medical Technologist",
    "Forensic Scientist",
    "Epidemiologist",
    "Public Health Educator",
    "Healthcare Administrator",
    "Health Informatics Specialist",
    "Clinical Psychologist",
    "Counselor",
    "Social Worker",
    "Behavior Analyst",
    "Speech-Language Pathologist",
    "Occupational Therapist",
    "Physical Therapist",
    "Dietitian/Nutritionist",
    "Exercise Physiologist",
    "Athletic Trainer",
    "Sports Coach",
    "Personal Trainer",
    "Massage Therapist",
    "Yoga Instructor",
    "Fitness Instructor",
    "Dentist",
    "Dental Hygienist",
    "Orthodontist",
    "Oral and Maxillofacial Surgeon",
    "Veterinarian",
    "Veterinary Technician",
    "Pet Groomer",
    "Zoologist",
    "Wildlife Biologist",
    "Marine Biologist",
    "Botanist",
    "Ecologist",
    "Forester",
    "Agricultural Scientist",
    "Farm Manager",
    "Agronomist",
    "Horticulturist",
    "Florist",
    "Agricultural Extension Officer",
    "Environmental Scientist",
    "Environmental Consultant",
    "Environmental Engineer",
    "Climate Scientist",
    "Meteorologist",
    "Oceanographer",
    "Seismologist",
    "Volcanologist",
    "Geographer",
    "Cartographer",
    "Urban Planner",
    "Landscape Architect",
    "Surveyor",
    "Civil Engineer",
    "Structural Engineer",
    "Transportation Engineer",
    "Electrical Engineer",
    "Mechanical Engineer",
    "Chemical Engineer",
    "Materials Engineer",
    "Automotive Engineer",
    "Aerospace Engineer",
    "Biomedical Engineer",
    "Nuclear Engineer",
    "Robotics Engineer",
    "Energy Engineer",
    "Renewable Energy Engineer",
    "Power Systems Engineer",
    "Computer Engineer",
    "Software Engineer",
    "Network Engineer",
    "Telecommunications Engineer",
    "Database Administrator",
    "System Administrator",
    "Information Security Analyst",
    "Data Scientist",
    "Machine Learning Engineer",
    "Artificial Intelligence (AI) Engineer",
    "Robotics Engineer",
    "Mechatronics Engineer",
    "Electronics Engineer",
    "Embedded Systems Engineer",
    "Control Systems Engineer",
    "Biotechnology Engineer",
    "Bioprocess Engineer",
    "Genetic Engineer",
    "Biomedical Engineer",
    "Pharmaceutical Engineer",
    "Chemical Analyst",
    "Process Engineer",
    "Quality Control Engineer",
    "Health and Safety Engineer",
    "Materials Scientist",
    "Metallurgical Engineer",
    "Mining Engineer",
    "Geotechnical Engineer",
    "Petroleum Engineer",
    "Environmental Engineer",
    "Water Resources Engineer",
    "Transportation Engineer",
    "Structural Engineer",
    "Construction Manager",
    "Architectural Drafter",
    "Land Surveyor",
    "Landscape Architect",
    "Interior Designer",
    "Urban Planner",
    "Civil Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Chemical Engineer",
    "Automotive Engineer",
    "Aerospace Engineer",
    "Nuclear Engineer",
    "Materials Engineer",
    "Industrial Engineer",
    "Manufacturing Engineer",
    "Process Engineer",
    "Quality Control Engineer",
    "Safety Engineer",
    "Systems Engineer",
    "Robotics Engineer",
    "Renewable Energy Engineer",
    "Energy Engineer",
    "Power Systems Engineer",
    "Research Scientist",
    "Lab Technician",
    "Clinical Research Coordinator",
    "Medical Technologist",
    "Forensic Scientist",
    "Epidemiologist",
    "Public Health Educator",
    "Healthcare Administrator",
    "Health Informatics Specialist",
    "Clinical Psychologist",
    "Counselor",
    "Social Worker",
    "Behavior Analyst",
    "Speech-Language Pathologist",
    "Occupational Therapist",
    "Physical Therapist",
    "Dietitian/Nutritionist",
    "Exercise Physiologist",
    "Athletic Trainer",
    "Sports Coach",
    "Personal Trainer",
    "Massage Therapist",
    "Yoga Instructor",
    "Fitness Instructor",
    "Dentist",
    "Dental Hygienist",
    "Orthodontist",
    "Oral and Maxillofacial Surgeon",
    "Veterinarian",
    "Veterinary Technician",
    "Pet Groomer",
    "Zoologist",
    "Wildlife Biologist",
    "Marine Biologist",
    "Botanist",
    "Ecologist",
    "Forester",
    "Agricultural Scientist",
    "Farm Manager",
    "Agronomist",
    "Horticulturist",
    "Florist",
    "Agricultural Extension Officer",
    "Environmental Scientist",
    "Environmental Consultant",
    "Environmental Engineer",
    "Climate Scientist",
    "Meteorologist",
    "Oceanographer",
    "Seismologist",
    "Volcanologist",
    "Geographer",
    "Cartographer",
    "Urban Planner",
    "Landscape Architect",
    "Surveyor",
    "Civil Engineer",
    "Structural Engineer",
    "Transportation Engineer",
    "Electrical Engineer",
    "Mechanical Engineer",
    "Chemical Engineer",
    "Materials Engineer",
    "Automotive Engineer",
    "Aerospace Engineer",
    "Biomedical Engineer",
    "Nuclear Engineer",
    "Robotics Engineer",
    "Energy Engineer",
    "Renewable Energy Engineer",
    "Power Systems Engineer",
    "Computer Engineer",
    "Software Engineer",
    "Network Engineer",
    "Telecommunications Engineer",
    "Database Administrator",
    "System Administrator",
    "Information Security Analyst",
    "Data Scientist",
    "Machine Learning Engineer",
    "Artificial Intelligence (AI) Engineer",
    "Robotics Engineer",
    "Mechatronics Engineer",
    "Electronics Engineer",
    "Embedded Systems Engineer",
    "Control Systems Engineer",
    "Biotechnology Engineer",
    "Bioprocess Engineer",
    "Genetic Engineer",
    "Biomedical Engineer",
    "Pharmaceutical Engineer",
    "Chemical Analys",
    "Student"
  ];

  export const FamousDegreesInPakistan = [
    "Matriculation (SSC)",
    "Intermediate (HSSC)",
    "Bachelor of Science (B.Sc.)",
    "Bachelor of Arts (B.A.)",
    "Bachelor of Commerce (B.Com.)",
    "Bachelor of Business Administration (BBA)",
    "Bachelor of Engineering (B.E.)",
    "Bachelor of Computer Science (BSCS)",
    "Doctor of Medicine (M.B.B.S.)",
    "Bachelor of Laws (LL.B.)",
    "Master of Business Administration (MBA)",
    "Master of Science (M.Sc.)",
    "Master of Arts (M.A.)",
    "Master of Computer Science (MSCS)",
    "Master of Philosophy (M.Phil.)",
    "Doctor of Philosophy (Ph.D.)",
    "Bachelor of Dental Surgery (BDS)",
    "Bachelor of Pharmacy (B.Pharm)",
    "Bachelor of Fine Arts (BFA)",
    "Master of Fine Arts (MFA)",
    "Bachelor of Education (B.Ed.)",
    "Master of Education (M.Ed.)",
  ];
  