export const Cars = [
    {
        'title':'Rolls Royce',
        'image':'/images/cars/phantom1.jpg',
        'make':'2020',
        'model':'Phantom',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':58000,
        'isFeatured':true,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Rolls Royce',
        'image':'/images/cars/sweptail.jpg',
        'make':'2020',
        'model':'Sweptail',
        'mileage':'1030 KM',
        'price':'360K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':105000,
        'isFeatured':true,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/gvegan1.jpeg',
        'make':'2020',
        'model':'G-Vegan',
        'mileage':'1139 KM',
        'price':'140K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':46000,
        'isFeatured':true,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Rolls Royce',
        'image':'/images/cars/ghost1.jpg',
        'make':'2020',
        'model':'Ghost',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Rolls Royce',
        'image':'/images/cars/ghost2.jpg',
        'make':'2020',
        'model':'Ghost',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'GMC',
        'image':'/images/cars/gmc1.png',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },

    {
        'title':'Toyota',
        'image':'/images/cars/grande1.png',
        'make':'2017',
        'model':'Grande',
        'mileage':'3000 KM',
        'price':'25K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':58000,
        'isFeatured':true,
        'category':'sedan',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/cam1.jpg',
        'make':'2020',
        'model':'Camery',
        'mileage':'1030 KM',
        'price':'50K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':105000,
        'isFeatured':true,
        'category':'sedan',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/ev.jpg',
        'make':'2020',
        'model':'E-V',
        'mileage':'1139 KM',
        'price':'140K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':46000,
        'isFeatured':true,
        'category':'sedan',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/cclass.jpeg',
        'make':'2020',
        'model':'C-Class',
        'mileage':'1139 KM',
        'price':'140K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':46000,
        'isFeatured':true,
        'category':'sedan',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/cclass.jpeg',
        'make':'2020',
        'model':'C-Class',
        'mileage':'1139 KM',
        'price':'140K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':46000,
        'isFeatured':true,
        'category':'sedan',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'GMC',
        'image':'/images/cars/gmc1.jpg',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'300 KM',
        'price':'200K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/land1.png',
        'make':'2010',
        'model':'Land Cruiser',
        'mileage':'5500 KM',
        'price':'119K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'GMC',
        'image':'/images/cars/gmc2.jpg',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'GMC',
        'image':'/images/cars/gmc3.jpg',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'1000 KM',
        'price':'180K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'suv',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'GMC',
        'image':'/images/cars/amg.jpeg',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'suv',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/gvegan3.jpeg',
        'make':'2020',
        'model':'G Vegan',
        'mileage':'105 KM',
        'price':'290K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'suv',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Ferrari',
        'image':'/images/cars/ferarri1.jpg',
        'make':'2020',
        'model':'F430',
        'mileage':'New',
        'price':'480K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Lamorgini',
        'image':'/images/cars/lambo1.jpg',
        'make':'2023',
        'model':'Hurracan',
        'mileage':'New',
        'price':'650K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'Mustang',
        'image':'/images/cars/mustang.jpeg',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },
    {
        'title':'GMC',
        'image':'/images/cars/gmc2.jpg',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus quaerat blanditiis eveniet provident odio fuga atque, animi porro molestiae ullam fugiat. Officiis est magnam nulla sit. Praesentium iure perspiciatis quis!Consequuntur eos ipsum blanditiis quasi, qui excepturi molestias iure ad quos cum facilis eveniet fugiat harum autem perspiciatis nam debitis necessitatibus exercitationem illo incidunt dicta sed ipsa? Quam, sed eveniet.Veniam aliquam ratione possimus ex voluptas officia reprehenderit dicta porro delectus, libero, ad aliquid deserunt amet inventore sint! Et, sapiente repudiandae. Illo sequi alias iure quaerat. Ad porro dolorum similique. Ad vitae corrupti id numquam, ea ipsum eaque sed! Sint enim, iure aperiam architecto, vel voluptatum dolorem inventore provident facilis ut doloribus quia nemo? Explicabo, consequatur itaque? Cumque, ad architecto'
    },

    
]