export const Cars = [
    {
        'title':'Rolls Royce',
        'image':'/images/cars/phantom1.jpg',
        'make':'2020',
        'model':'Phantom',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':58000,
        'isFeatured':true,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Rolls Royce',
        'image':'/images/cars/sweptail.jpg',
        'make':'2020',
        'model':'Sweptail',
        'mileage':'1030 KM',
        'price':'360K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':105000,
        'isFeatured':true,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/gvegan1.jpeg',
        'make':'2020',
        'model':'G-Vegan',
        'mileage':'1139 KM',
        'price':'140K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':46000,
        'isFeatured':true,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Ferarri',
        'image':'/images/cars/ferarri3.jpg',
        'make':'2020',
        'model':'F430',
        'mileage':'NEW',
        'price':'350K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Lamorgini',
        'image':'/images/cars/lambo1.jpg',
        'make':'2023',
        'model':'Hurracan',
        'mileage':'NEW',
        'price':'650K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Mustang',
        'image':'/images/cars/mustang1.jpg',
        'make':'1985',
        'model':'Mustang',
        'mileage':'300 KM',
        'price':'200K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },

    {
        'title':'Toyota',
        'image':'/images/cars/grande1.png',
        'make':'2017',
        'model':'Grande',
        'mileage':'3000 KM',
        'price':'25K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':58000,
        'isFeatured':true,
        'category':'sedan',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/cam1.jpg',
        'make':'2020',
        'model':'Camery',
        'mileage':'1030 KM',
        'price':'50K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':105000,
        'isFeatured':true,
        'category':'sedan',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/ev.jpg',
        'make':'2020',
        'model':'E-V',
        'mileage':'1139 KM',
        'price':'140K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':46000,
        'isFeatured':true,
        'category':'sedan',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/cclass.jpeg',
        'make':'2020',
        'model':'C-Class',
        'mileage':'1139 KM',
        'price':'140K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':46000,
        'isFeatured':true,
        'category':'sedan',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/cclass.jpeg',
        'make':'2020',
        'model':'C-Class',
        'mileage':'1139 KM',
        'price':'140K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':46000,
        'isFeatured':true,
        'category':'sedan',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'GMC',
        'image':'/images/cars/gmc1.jpg',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'300 KM',
        'price':'200K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/land1.png',
        'make':'2010',
        'model':'Land Cruiser',
        'mileage':'5500 KM',
        'price':'119K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'GMC',
        'image':'/images/cars/gmc2.jpg',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/vclass.jpeg',
        'make':'2023',
        'model':'V Class',
        'mileage':'1000 KM',
        'price':'80K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'suv',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/revo1.jpeg',
        'make':'2020',
        'model':'Revo ',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'suv',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/gvegan3.jpeg',
        'make':'2020',
        'model':'G Vegan',
        'mileage':'105 KM',
        'price':'290K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'suv',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Ferrari',
        'image':'/images/cars/ferarri1.jpg',
        'make':'2020',
        'model':'F430',
        'mileage':'New',
        'price':'480K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Lamorgini',
        'image':'/images/cars/lambo1.jpg',
        'make':'2023',
        'model':'Hurracan',
        'mileage':'New',
        'price':'650K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Mustang',
        'image':'/images/cars/mustang.jpeg',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'GMC',
        'image':'/images/cars/gmc2.jpg',
        'make':'2020',
        'model':'Land Rover',
        'mileage':'1500 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'trucks',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Mercedes',
        'image':'/images/cars/gvegan2.jpeg',
        'make':'2020',
        'model':'G Vegan',
        'mileage':'300 KM',
        'price':'180K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/crown1.png',
        'make':'2024',
        'model':'Crown',
        'mileage':'1500 KM',
        'price':'120K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/crown2.png',
        'make':'2014',
        'model':'Crown',
        'mileage':'100 KM',
        'price':'50K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/crown3.png',
        'make':'2019',
        'model':'Crown',
        'mileage':'1500 KM',
        'price':'120K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/crv.jpeg',
        'make':'2020',
        'model':'CRV',
        'mileage':'350 KM',
        'price':'90K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Honda',
        'image':'/images/cars/crz.jpeg',
        'make':'2024',
        'model':'CRZ',
        'mileage':'100 KM',
        'price':'60K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':50000,
        'isFeatured':false,
        'category':'luxury',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    
    {
        'title':'Toyota',
        'image':'/images/cars/sp1.jpg',
        'make':'1994',
        'model':'Supra ',
        'mileage':'10000 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':655000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/sp2.jpg',
        'make':'1994',
        'model':'Supra ',
        'mileage':'10000 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':655000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Toyota',
        'image':'/images/cars/sp3.jpg',
        'make':'1994',
        'model':'Supra ',
        'mileage':'10000 KM',
        'price':'250K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':655000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Nissan',
        'image':'/images/cars/ns1.jpg',
        'make':'1997',
        'model':'GTR R-34 ',
        'mileage':'181000 KM',
        'price':'205K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':555000,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Nissan',
        'image':'/images/cars/ns2.jpg',
        'make':'1994',
        'model':'GTR R-34 ',
        'mileage':'30000 KM',
        'price':'290K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':135090,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Nissan',
        'image':'/images/cars/ns3.jpg',
        'make':'1983',
        'model':'GTR R-34 ',
        'mileage':'50000 KM',
        'price':'490K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':106090,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Lamborgini',
        'image':'/images/cars/lambo2.jpg',
        'make':'2014',
        'model':'Glardo',
        'mileage':'3000 KM',
        'price':'1.3M',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':135090,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    {
        'title':'Lamborgini',
        'image':'/images/cars/lambo3.jpg',
        'make':'2019',
        'model':' Huraccan',
        'mileage':'30000 KM',
        'price':'290K',
        'currency':'$',
        'owner':'Ahmad Raza Khokhar',
        'location':'Arfa Tower, Lahore',
        'likes':135090,
        'isFeatured':false,
        'category':'sports',
        'description':'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae fuga blanditiis fugit! Repellendus accusantium animi amet unde asperiores alias veniam ad harum modi non quam, dolorum voluptatum quasi earum eaAliquam, veniam deleniti tempora minus fugit ducimus vitae, necessitatibus.',
        'phone':'03008039275'
    },
    
]